/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela_principal;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import tela_equipamentos.TelaEquipamentos;

/**
 *
 * @author hugos
 */
public class BarraPesquisar extends javax.swing.JFrame {

    /**
     * Creates new form BarraPesquisar
     */
    private TelaPrincipal tp;

    public BarraPesquisar(TelaPrincipal tp) {
        initComponents();
        this.tp = tp;
        setLocation(100, 14);
        setBackground(new java.awt.Color(0, 0, 0, 0));

        campo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = campo.getText().trim();
                TelaEquipamentos.getInstancia().filtrarEquipamentos(texto);
            }
        });

        // Eventos da janela
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                TelaEquipamentos.getInstancia().filtrarEquipamentos("");
            }
        });

        // 🔹 Evento de foco no campo — fecha e limpa se clicar fora
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                TelaEquipamentos.getInstancia().filtrarEquipamentos("");
                dispose();
            }
        });
    }

    // Evento de digitação (pesquisa em tempo real)
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 65));
        setMinimumSize(new java.awt.Dimension(600, 65));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        campo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campo.setBorder(null);
        getContentPane().add(campo);
        campo.setBounds(20, 12, 560, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barra_pesquisar.png"))); // NOI18N
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 65);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
