package tela_principal;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Hugo, Alex
 */
public class BarraPesquisar extends javax.swing.JFrame {

    // Referência à tela principal
    private TelaPrincipal tp;
    private JTable tabela; // tabela encontrada automaticamente

    public BarraPesquisar(TelaPrincipal tp) {
        initComponents();
        this.tp = tp;
        setLocation(100, 14);
        setBackground(new java.awt.Color(0, 0, 0, 0));

        // 🔍 Procura automaticamente uma JTable dentro da tela principal
        tabela = encontrarTabela(tp.getContentPane());

        // Atualiza a tabela conforme o usuário digita
        campo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = campo.getText().trim();
                if (tabela != null) {
                    aplicarFiltroTabela(tabela, texto);
                }
            }
        });

        // Fecha a janela ao perder o foco
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });

        // 🔹 Fecha ao clicar fora do campo
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                dispose();
            }
        });
    }

    /**
     * Procura uma JTable dentro do container (recursivamente)
     */
    private JTable encontrarTabela(Container container) {
        for (Component comp : container.getComponents()) {
            if (comp instanceof JTable tabela) {
                return tabela;
            } else if (comp instanceof Container filho) {
                JTable t = encontrarTabela(filho);
                if (t != null) {
                    return t;
                }
            }
        }
        return null;
    }

    /**
     * Aplica o filtro digitado à tabela
     */
    private void aplicarFiltroTabela(JTable tabela, String texto) {
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tabela.getModel());
        tabela.setRowSorter(sorter);

        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto)); // busca ignorando maiúsculas/minúsculas
        }
    }

    // Evento de digitação (pesquisa em tempo real)
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 65));
        setMinimumSize(new java.awt.Dimension(600, 65));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        campo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campo.setBorder(null);
        getContentPane().add(campo);
        campo.setBounds(20, 12, 560, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barra_pesquisar.png"))); // NOI18N
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 65);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}