package tela_equipamentos;

import controllers.EquipamentosDAO;
import models.Equipamentos;

/**
 *
 * @author Hugo
 */
public class CadastroEquipamentos extends javax.swing.JFrame {

    private TelaEquipamentos telaEquipamentos;

    // Passando a referência da tela.
    public CadastroEquipamentos(TelaEquipamentos tela) {
        initComponents();
        this.telaEquipamentos = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtSoldador = new javax.swing.JTextField();
        botaoCancelar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(770, 480));
        setMinimumSize(new java.awt.Dimension(770, 480));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 58, 138), 2, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(770, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 480));
        jPanel1.setLayout(null);

        combo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estoque", "Emprestado", "Estragado" }));
        jPanel1.add(combo);
        combo.setBounds(300, 300, 450, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Soldador");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 250, 150, 32);

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtMarca);
        txtMarca.setBounds(300, 200, 450, 30);

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtModelo.setToolTipText("");
        jPanel1.add(txtModelo);
        txtModelo.setBounds(300, 150, 450, 30);

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(300, 100, 450, 30);

        txtSoldador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoldador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoldadorKeyReleased(evt);
            }
        });
        jPanel1.add(txtSoldador);
        txtSoldador.setBounds(300, 250, 450, 30);

        botaoCancelar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoCancelar.setText("CANCELAR");
        botaoCancelar.setMaximumSize(new java.awt.Dimension(260, 83));
        botaoCancelar.setMinimumSize(new java.awt.Dimension(260, 83));
        botaoCancelar.setPreferredSize(new java.awt.Dimension(260, 83));
        botaoCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(botaoCancelar);
        botaoCancelar.setBounds(40, 370, 260, 83);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Estado de Uso");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 300, 160, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Modelo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 150, 90, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Marca");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 140, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Código");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 150, 32);

        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.setMaximumSize(new java.awt.Dimension(260, 83));
        botaoCadastrar.setMinimumSize(new java.awt.Dimension(260, 83));
        botaoCadastrar.setPreferredSize(new java.awt.Dimension(260, 83));
        botaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseClicked(evt);
            }
        });
        jPanel1.add(botaoCadastrar);
        botaoCadastrar.setBounds(470, 370, 260, 83);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR EQUIPAMENTO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 770, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastro_botao.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 370, 260, 83);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastro_botao.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 370, 260, 83);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseClicked
        // Recebendo os valores cadastrados.
        String codigo = txtCodigo.getText();
        String modelo = txtModelo.getText();
        String marca = txtMarca.getText();
        String soldador = txtSoldador.getText();
        String condicao = combo.getSelectedItem().toString().toLowerCase();
        
        // Enviando o cadastro.
        Equipamentos eq = new Equipamentos();
        eq.setCodigo(codigo);
        eq.setModelo(modelo);
        eq.setMarca(marca);
        eq.setSoldador(soldador);
        eq.setCondicao(condicao);
        
        // Utilizando o método 'atualizarEquipamento' da classe DAO.
        EquipamentosDAO dao = new EquipamentosDAO();
        dao.inserirEquipamento(eq);

        // Atualiza a tabela da tela principal
        if (telaEquipamentos != null) {
            telaEquipamentos.carregarTabela();
        }

        this.dispose(); // fecha a tela
    }//GEN-LAST:event_botaoCadastrarMouseClicked

    private void botaoCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_botaoCancelarMouseClicked

    private void txtSoldadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoldadorKeyReleased
        // Comando para ajudar o usuário com a logica do banco.
        // Caso preencha o campo "soldador", a combo box será trancada no item "Emprestado".
        // No contrario, irá para o item "Estoque".
        String soldador = txtSoldador.getText().trim();

        if (!soldador.isEmpty()) {
            combo.setSelectedItem("Emprestado");
            combo.setEnabled(false);
        } else {
            combo.setSelectedItem("Estoque");
            combo.setEnabled(true);
        }
    }//GEN-LAST:event_txtSoldadorKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoCadastrar;
    private javax.swing.JLabel botaoCancelar;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSoldador;
    // End of variables declaration//GEN-END:variables
}
