/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tela_conta;

import models.Usuarios;
import tela_login.TelaLogin;
import util.Fonte;

/**
 *
 * @author hugos
 */
public class TelaConta extends javax.swing.JPanel {

    /**
     * Creates new form TelaConta
     */
    public TelaConta() {
        initComponents();
        String nome = Sessao.usuarioLogado.getNome();
        nomeUser.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        manualUsuario = new javax.swing.JLabel();
        trocarSenha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(228, 228, 228));
        setMaximumSize(new java.awt.Dimension(1810, 1014));
        setMinimumSize(new java.awt.Dimension(1810, 1014));
        setPreferredSize(new java.awt.Dimension(1810, 1014));
        setLayout(null);

        nomeUser.setFont(Fonte.inserirFonte("Baloo2-Bold.ttf", 46f));
        nomeUser.setForeground(new java.awt.Color(112, 112, 112));
        nomeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(nomeUser);
        nomeUser.setBounds(1200, 546, 550, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_card.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(1190, 30, 580, 960);

        manualUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manual.png"))); // NOI18N
        manualUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manualUsuarioMouseClicked(evt);
            }
        });
        add(manualUsuario);
        manualUsuario.setBounds(110, 600, 950, 160);

        trocarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/senha.png"))); // NOI18N
        trocarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trocarSenhaMouseClicked(evt);
            }
        });
        add(trocarSenha);
        trocarSenha.setBounds(110, 180, 950, 160);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tema.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(110, 390, 950, 160);
    }// </editor-fold>//GEN-END:initComponents

    private void manualUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manualUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manualUsuarioMouseClicked

    private void trocarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trocarSenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trocarSenhaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel manualUsuario;
    private javax.swing.JLabel nomeUser;
    private javax.swing.JLabel trocarSenha;
    // End of variables declaration//GEN-END:variables
}
